# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 603d1be2382b7294a25816598ddb66660fd9b2ee0cfba1557cd29d84fdeb4edbcc0462037e3075c0c1eecbac0aa671c6248cc0d2c72ea1adaa334509a9c9fada

test:
  secret_key_base: d39d7065889d242d9c7d40e49a46138cf0a156611876b1455465b4bf6c1acb8ef519399a549c060b3ca348845943e7755d2e9b8b3a96adc989195523a7972132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
